### ISSUE TITLE
[BUG] v2raya 启动失败 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ayalhw** [mzz2017/v2rayA#14]
**描述问题**
简要描述问题
v2raya 启动失败

**复现问题的步骤**
如何复现问题
安装0.5.9，启动v2raya

**预期结果**
简要讲述执行正确时预期的结果
正常启动

**截图**
如果条件允许请附图
以下是log
```
1月 05 11:06:32 lhw-laptap audit[32210]: USER_ACCT pid=32210 uid=1000 auid=1000 ses=2 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="lhw" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=success'
1月 05 11:06:32 lhw-laptap sudo[32210]:      lhw : TTY=pts/3 ; PWD=/home/lhw ; USER=root ; COMMAND=/usr/bin/systemctl start v2raya
1月 05 11:06:32 lhw-laptap audit[32210]: CRED_REFR pid=32210 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_unix,pam_permit,pam_env acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=success'
1月 05 11:06:32 lhw-laptap audit[32210]: USER_START pid=32210 uid=0 auid=1000 ses=2 msg='op=PAM:session_open grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=success'
1月 05 11:06:32 lhw-laptap sudo[32210]: pam_unix(sudo:session): session opened for user root by lhw(uid=0)
1月 05 11:06:32 lhw-laptap kernel: audit: type=1101 audit(1578193592.711:349): pid=32210 uid=1000 auid=1000 ses=2 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="lhw" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/>
1月 05 11:06:32 lhw-laptap kernel: audit: type=1110 audit(1578193592.711:350): pid=32210 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_unix,pam_permit,pam_env acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=>
1月 05 11:06:32 lhw-laptap kernel: audit: type=1105 audit(1578193592.711:351): pid=32210 uid=0 auid=1000 ses=2 msg='op=PAM:session_open grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pt>
1月 05 11:06:32 lhw-laptap systemd[1]: Started V2RayA Service.
-- Subject: v2raya.service 单元已结束启动
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- v2raya.service 单元已结束启动。
-- 
-- 启动结果为“done”。
1月 05 11:06:32 lhw-laptap audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=v2raya comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
1月 05 11:06:32 lhw-laptap audit[32210]: USER_END pid=32210 uid=0 auid=1000 ses=2 msg='op=PAM:session_close grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=success'
1月 05 11:06:32 lhw-laptap audit[32210]: CRED_DISP pid=32210 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_unix,pam_permit,pam_env acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=success'
1月 05 11:06:32 lhw-laptap sudo[32210]: pam_unix(sudo:session): session closed for user root
1月 05 11:06:32 lhw-laptap kernel: audit: type=1130 audit(1578193592.721:352): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=v2raya comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
1月 05 11:06:32 lhw-laptap kernel: audit: type=1106 audit(1578193592.721:353): pid=32210 uid=0 auid=1000 ses=2 msg='op=PAM:session_close grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/p>
1月 05 11:06:32 lhw-laptap kernel: audit: type=1104 audit(1578193592.721:354): pid=32210 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_unix,pam_permit,pam_env acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/3 res=>
1月 05 11:06:32 lhw-laptap v2raya[32213]: V2RayLocationAsset is /usr/lib/v2ray
1月 05 11:06:32 lhw-laptap v2raya[32213]: V2Ray binary is at /usr/lib/v2ray/v2ray
1月 05 11:06:32 lhw-laptap v2raya[32213]: V2RayA working directory is /
1月 05 11:06:32 lhw-laptap v2raya[32213]: Version: 0.5.9
1月 05 11:06:32 lhw-laptap v2raya[32213]: V2RayA is running at 0.0.0.0:2017
1月 05 11:06:32 lhw-laptap v2raya[32213]: panic: runtime error: invalid memory address or nil pointer dereference
1月 05 11:06:32 lhw-laptap v2raya[32213]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x562c8a7a7ae6]
1月 05 11:06:32 lhw-laptap v2raya[32213]: goroutine 1 [running]:
1月 05 11:06:32 lhw-laptap v2raya[32213]: V2RayA/model/v2ray.NewTemplateFromVmessInfo(0xc000604290, 0xc, 0xc0006042a0, 0xd, 0xc0006042b4, 0x5, 0xc0005f2930, 0x24, 0xc0006042c0, 0x2, ...)
1月 05 11:06:32 lhw-laptap v2raya[32213]:         /home/lhw/.cache/yay/v2raya/src/V2RayA-0.5.9/service/model/v2ray/v2rayTmpl.go:364 +0x406
1月 05 11:06:32 lhw-laptap v2raya[32213]: V2RayA/model/v2ray.UpdateV2rayWithConnectedServer(0x562c8a104a70, 0xc00045bea0)
1月 05 11:06:32 lhw-laptap v2raya[32213]:         /home/lhw/.cache/yay/v2raya/src/V2RayA-0.5.9/service/model/v2ray/status.go:212 +0xf0
1月 05 11:06:32 lhw-laptap v2raya[32213]: main.run(0xc000000180, 0xc000193f50)
1月 05 11:06:32 lhw-laptap v2raya[32213]:         /home/lhw/.cache/yay/v2raya/src/V2RayA-0.5.9/service/main.go:200 +0x4a
1月 05 11:06:32 lhw-laptap v2raya[32213]: main.main()
1月 05 11:06:32 lhw-laptap v2raya[32213]:         /home/lhw/.cache/yay/v2raya/src/V2RayA-0.5.9/service/main.go:234 +0xaf
1月 05 11:06:32 lhw-laptap systemd[1]: v2raya.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- An ExecStart= process belonging to unit v2raya.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 2.
1月 05 11:06:32 lhw-laptap systemd[1]: v2raya.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit v2raya.service has entered the 'failed' state with result 'exit-code'.
1月 05 11:06:32 lhw-laptap audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=v2raya comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
1月 05 11:06:32 lhw-laptap kernel: audit: type=1131 audit(1578193592.841:355): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=v2raya comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
1月 05 11:06:32 lhw-laptap systemd[1]: v2raya.service: Scheduled restart job, restart counter is at 1.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Automatic restarting of the unit v2raya.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
1月 05 11:06:32 lhw-laptap systemd[1]: Stopped V2RayA Service.
-- Subject: v2raya.service 单元已结束停止操作
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- v2raya.service 单元已结束停止操作。
```
看着是访问越界

**Comment by ayalhw** [comment]
install from AUR

**Comment by ayalhw** [comment]
OK，it works well now at `0.5.9.1`

**Comment by hfutxqd** [comment]
v0.7.1.1 出现此问题
系统：Arch Linux
内核：Linux 5.7.2
CPU：AMD 2700X

**Comment by mzz2017** [comment]
> v0.7.1.1 出现此问题
> 系统：Arch Linux
> 内核：Linux 5.7.2
> CPU：AMD 2700X

请提供下详细日志，谢谢

**Comment by hfutxqd** [comment]
> > v0.7.1.1 出现此问题
> > 系统：Arch Linux
> > 内核：Linux 5.7.2
> > CPU：AMD 2700X
> 
> 请提供下详细日志，谢谢

已在原回复中提供

**Comment by mzz2017** [comment]
使用过之前的版本是吗

**Comment by hfutxqd** [comment]
> 使用过之前的版本是吗

需要尝试清除配置么？我试试

**Comment by mzz2017** [comment]
可能是迁移过程中出现了问题，发生几率不高，按理说只能是因为之前的配置迁移失败了

**Comment by hfutxqd** [comment]
> 使用过之前的版本是吗

清除配置文件后工作正常

**Comment by mzz2017** [comment]
好的，谢谢，我会加一些代码来使得程序更加健硕
